// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    folders,
    files,
    recents,
    recentsKeep20,
    favourites,
    versions,
    versionsKeep5,
    trash,
    ocrText,
    pinnedTools,
    toolUsage,
    proTrials,
    workflows,
    signatures,
    photoFinderCache,
    jobs,
  ];
  late final Shape0 folders = Shape0(
    source: i0.VersionedTable(
      entityName: 'folders',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 files = Shape1(
    source: i0.VersionedTable(
      entityName: 'files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_4,
        _column_2,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 recents = Shape2(
    source: i0.VersionedTable(
      entityName: 'recents',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger recentsKeep20 = i1.Trigger(
    'CREATE TRIGGER recents_keep_20 AFTER INSERT ON recents BEGIN DELETE FROM recents WHERE file_id NOT IN (SELECT file_id FROM recents ORDER BY opened_at DESC LIMIT 20);END',
    'recents_keep_20',
  );
  late final Shape3 favourites = Shape3(
    source: i0.VersionedTable(
      entityName: 'favourites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_13, _column_15],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 versions = Shape4(
    source: i0.VersionedTable(
      entityName: 'versions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_16, _column_17, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger versionsKeep5 = i1.Trigger(
    'CREATE TRIGGER versions_keep_5 AFTER INSERT ON versions BEGIN DELETE FROM versions WHERE file_id = new.file_id AND id NOT IN (SELECT id FROM versions WHERE file_id = new.file_id ORDER BY created_at DESC, id DESC LIMIT 5);END',
    'versions_keep_5',
  );
  late final Shape5 trash = Shape5(
    source: i0.VersionedTable(
      entityName: 'trash',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_13, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 ocrText = Shape6(
    source: i0.VersionedVirtualTable(
      entityName: 'ocr_text',
      moduleAndArgs: 'fts5(file_id UNINDEXED, page UNINDEXED, page_text, tokenize = \'unicode61 remove_diacritics 2\')',
      columns: [_column_20, _column_21, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 pinnedTools = Shape7(
    source: i0.VersionedTable(
      entityName: 'pinned_tools',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_23, _column_24],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 toolUsage = Shape8(
    source: i0.VersionedTable(
      entityName: 'tool_usage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_23, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 proTrials = Shape9(
    source: i0.VersionedTable(
      entityName: 'pro_trials',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_23, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 workflows = Shape10(
    source: i0.VersionedTable(
      entityName: 'workflows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_2, _column_28, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 signatures = Shape11(
    source: i0.VersionedTable(
      entityName: 'signatures',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_29, _column_30, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 photoFinderCache = Shape12(
    source: i0.VersionedTable(
      entityName: 'photo_finder_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_31, _column_8, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 jobs = Shape13(
    source: i0.VersionedTable(
      entityName: 'jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_34, _column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get parentId =>
      columnsByName['parent_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get colourTag =>
      columnsByName['colour_tag']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'parent_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'REFERENCES folders(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'colour_tag',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get size =>
      columnsByName['size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pages =>
      columnsByName['pages']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get modified =>
      columnsByName['modified']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hasText =>
      columnsByName['has_text']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get encrypted =>
      columnsByName['encrypted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get folderId =>
      columnsByName['folder_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get colour =>
      columnsByName['colour']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pages',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'modified',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'has_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const i1.CustomExpression('FALSE'),
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'encrypted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const i1.CustomExpression('FALSE'),
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'folder_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'REFERENCES folders(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'colour',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get fileId =>
      columnsByName['file_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get openedAt =>
      columnsByName['opened_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'file_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL PRIMARY KEY REFERENCES files(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'opened_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get fileId =>
      columnsByName['file_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get addedAt =>
      columnsByName['added_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'added_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fileId =>
      columnsByName['file_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'file_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES files(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get fileId =>
      columnsByName['file_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedVirtualTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get fileId =>
      columnsByName['file_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get page =>
      columnsByName['page']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pageText =>
      columnsByName['page_text']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'page',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'page_text',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get toolId =>
      columnsByName['tool_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tool_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get toolId =>
      columnsByName['tool_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get count =>
      columnsByName['count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastUsed =>
      columnsByName['last_used']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_used',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get toolId =>
      columnsByName['tool_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get usedAt =>
      columnsByName['used_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'used_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get steps =>
      columnsByName['steps']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'steps',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imageRef =>
      columnsByName['image_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (kind IN (\'signature\', \'initials\'))',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image_ref',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get assetId =>
      columnsByName['asset_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get modified =>
      columnsByName['modified']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get score =>
      columnsByName['score']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get isDocument =>
      columnsByName['is_document']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'asset_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<double> _column_32(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'score',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_document',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get toolId =>
      columnsByName['tool_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get input =>
      columnsByName['input']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tool_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'input',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
